--- #YAML:1.0
name:               Nagios-Plugin-IMAPQuota
version:            0.1
abstract:           Nagios plugin to monitor the quota usage of an IMAP mailbox.
author:
    - Tore A. Klock <alphapenguin73@gmail.com>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Mail::IMAPClient:  3.28
    Nagios::Plugin:    0.35
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
